### ISSUE TITLE
New build pipeline additional TODO

### ISSUE THREAD

**Issue by justvanrossum** [djrrb/Bungee#94]
- [ ] Implement a solution for the "exception" glyphs in the basic Shadow style (as drawn in 2-build)
- [ ] Check what other relevant differences exist between the released fonts and the fonts from this pipeline, usng diffenator2.
- [ ] Verify and fix spacing/kerning for vertical layout

(We may edit the above list as we discover/remember more items.)

**Comment by justvanrossum** [comment]
Vertical layout is currently quite broken.
