### ISSUE TITLE
Minor corrections for source file TODO

### ISSUE THREAD

**Issue by martelahaie** [djrrb/Bungee#96]
There are minor differences between the fonts in `sources/1-drawing` and `sources/2-build`. Adjusting these differences in the /1-drawings source file will ensure that the new build stays close to the original /2-build files.

- [x] Lslash.salt en Lslash.salt_v: contour inline reversed
- [x] Lslash.salt_v: slash 2 units up
- [x] Lslash.v: slash contours moved
- [x] Tbar.v: extra shade contour
- [x] one.sups, two.sups, three.sups, four.sups: extra contours
- [x] fi en fl: ligatures missing unicode
- [x] OE.v contour changed down left curve
- [x] semicolon.v: components have the non-vertical form as baseGlyphs
- [x] quotedblbase.v: non-vertical glyph as baseGlyph
- [x] periodcentered: add periodcentered.v for correct placement Rotated fonts
- [x] Uhorn and Ohorn: Inline connection modified
- [x] uni25DC, uni25DD, uni25DE, uni25DF: width of 1000 instead of 1280 (Rotated)
- [x] partialdiff & paragraph: remove unwanted "triangles" in contour
- [x] uni27A1.s & uni27A1.n: height is one unit too high
- [x] partialdiff, paragraph & exclamdown: wrong outline contours

**Comment by djrrb** [comment]
Thank you for catching all of these discrepancies! From my POV, you are welcome to move forward with whatever solution looks best.

**Comment by justvanrossum** [comment]
The new build doesn't use the 2-build folder at all, yet the original fonts were made from it. We'd like to propagate these inconsistencies (most likely: tweaks made in 2-build, after it was exported from 1-drawing) back to 1-drawing, so it will be our single source of truth :)

Once everything is done, we can delete 2-build, to avoid future confusion.

**Comment by djrrb** [comment]
Yes! Love it.
